name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag particlechromo3d:$(date +%s) --tag particlechromo3d:latest

    - name: Save docker image
      run: docker image save particlechromo3d:latest -o particlechromo3d_image.tar.gz

    - name: Upload docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: particlechromo3d_image
        path: particlechromo3d_image.tar.gz